# Generated by Django 4.0.5 on 2022-06-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_options_alter_contact_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='a', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='a', max_length=50),
        ),
    ]
