# Generated by Django 4.0.5 on 2022-06-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_last_name_contact_phone_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Resolved', 'Resolved')], default='New', max_length=50),
        ),
    ]
