# Generated by Django 4.0.5 on 2022-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_admin_update_contact_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
