# Generated by Django 4.0.5 on 2022-06-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pix',
            field=models.ImageField(default='download.jpg', upload_to='profile'),
        ),
    ]
