# Generated by Django 4.0.5 on 2022-06-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_shopcart_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='User',
            new_name='user',
        ),
    ]
