# Generated by Django 4.0.5 on 2022-07-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_user_shopcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='name_id',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
